$terminal = ghostty
$browser = zen-browser

exec-once = [workspace 1 silent] uwsm app -- $terminal
exec-once = [workspace 2 silent] uwsm app -- $browser
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- kanata
exec-once = uwsm app -- elephant
